<a href="https://colab.research.google.com/github/Nico-Cartes-dev/mineria-datos/blob/main/f1_colab_mineria_dat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("/content/drive/MyDrive/ai_impact_jobs_2010_2025.csv")
display(df.head())

,job_id,posting_year,country,region,city,company_name,company_size,industry,job_title,seniority_level,...,ai_intensity_score,core_skills,ai_skills,salary_usd,salary_change_vs_prev_year_percent,automation_risk_score,reskilling_required,ai_job_displacement_risk,job_description_embedding_cluster,industry_ai_adoption_stage
0,836b4774-702e-49ef-93d3-2f255ce1e910,2018,Brazil,South America,London,NextGen Technologies,Small,Education,Policy Analyst,Lead,...,0.81,"Research, Project Management, Business Analysis",reinforcement learning,61586,12.68,0.11,True,Low,14,Growing
1,43699e93-7b15-4728-a4c6-9e41ff438a25,2015,UAE,Middle East,Singapore,Future Solutions,Medium,Energy,Data Scientist,Executive,...,0.04,"Research, SQL, Business Analysis, Python, Clou...",NaN,62045,-3.98,0.71,False,High,19,Emerging
2,fc9d1854-3cbf-4bab-90df-77304dfc59df,2016,Nepal,South Asia,Sydney,Future Analytics,Startup,Finance,Product Manager,Junior,...,0.15,"Statistics, Project Management, Cloud Computin...",NaN,27035,3.55,0.86,False,High,2,Emerging
3,05c1c7d3-2add-4919-91eb-f6c78bfe23d1,2015,Spain,Europe,Nairobi,Global Technologies,Large,Government,Data Scientist,Mid,...,0.19,"Cloud Computing, SQL, Project Management, Comm...",NaN,72894,-2.80,0.70,False,Low,15,Emerging
4,5e739937-d1b0-44d7-935c-7ebb3fc1f6e8,2014,Taiwan,East Asia,Sydney,Future Technologies,Small,Manufacturing,ML Engineer,Lead,...,0.11,"SQL, Python, Communication, Software Engineeri...",NaN,57215,0.85,0.87,False,High,13,Emerging

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
df.columns

Index(['job_id', 'posting_year', 'country', 'region', 'city', 'company_name',
       'company_size', 'industry', 'job_title', 'seniority_level',
       'ai_mentioned', 'ai_keywords', 'ai_intensity_score', 'core_skills',
       'ai_skills', 'salary_usd', 'salary_change_vs_prev_year_percent',
       'automation_risk_score', 'reskilling_required',
       'ai_job_displacement_risk', 'job_description_embedding_cluster',
       'industry_ai_adoption_stage'],
      dtype='object')

In [ ]:
df.isnull().sum()

job_id                                   0
posting_year                             0
country                                  0
region                                   0
city                                     0
company_name                             0
company_size                             0
industry                                 0
job_title                                0
seniority_level                          0
ai_mentioned                             0
ai_keywords                           3377
ai_intensity_score                       0
core_skills                              0
ai_skills                             3377
salary_usd                               0
salary_change_vs_prev_year_percent       0
automation_risk_score                    0
reskilling_required                      0
ai_job_displacement_risk                 0
job_description_embedding_cluster        0
industry_ai_adoption_stage               0
dtype: int64

In [ ]:
df.describe().round()

,posting_year,ai_intensity_score,salary_usd,salary_change_vs_prev_year_percent,automation_risk_score,job_description_embedding_cluster
count,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0
mean,2018.0,0.0,63096.0,3.0,1.0,9.0
std,5.0,0.0,31431.0,6.0,0.0,6.0
min,2010.0,0.0,15321.0,-5.0,0.0,0.0
25%,2013.0,0.0,36576.0,-2.0,0.0,4.0
50%,2017.0,0.0,60910.0,2.0,1.0,10.0
75%,2022.0,1.0,81812.0,5.0,1.0,14.0
max,2025.0,1.0,161547.0,18.0,1.0,19.0

In [ ]:
df.shape

(5000, 22)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 22 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   job_id                              5000 non-null   object
 1   posting_year                        5000 non-null   int64
 2   country                             5000 non-null   object
 3   region                              5000 non-null   object
 4   city                                5000 non-null   object
 5   company_name                        5000 non-null   object
 6   company_size                        5000 non-null   object
 7   industry                            5000 non-null   object
 8   job_title                           5000 non-null   object
 9   seniority_level                     5000 non-null   object
 10  ai_mentioned                        5000 non-null   bool
 11  ai_keywords                         1623 non-null   object
 12  ai_intensity_score                  5000 non-null   float64
 13  core_skills                         5000 non-null   object
 14  ai_skills                           1623 non-null   object
 15  salary_usd                          5000 non-null   int64
 16  salary_change_vs_prev_year_percent  5000 non-null   float64
 17  automation_risk_score               5000 non-null   float64
 18  reskilling_required                 5000 non-null   bool
 19  ai_job_displacement_risk            5000 non-null   object
 20  job_description_embedding_cluster   5000 non-null   int64
 21  industry_ai_adoption_stage          5000 non-null   object
dtypes: bool(2), float64(3), int64(3), object(14)
memory usage: 791.1+ KB

In [ ]:
df.columns

Index(['job_id', 'posting_year', 'country', 'region', 'city', 'company_name',
       'company_size', 'industry', 'job_title', 'seniority_level',
       'ai_mentioned', 'ai_keywords', 'ai_intensity_score', 'core_skills',
       'ai_skills', 'salary_usd', 'salary_change_vs_prev_year_percent',
       'automation_risk_score', 'reskilling_required',
       'ai_job_displacement_risk', 'job_description_embedding_cluster',
       'industry_ai_adoption_stage'],
      dtype='object')

In [ ]:
df["industry"].value_counts()
df["country"].value_counts()
df.groupby("industry")["salary_usd"].mean()
df.groupby("posting_year")["salary_usd"].mean()
df.groupby("country")["automation_risk_score"].mean()

country
Argentina         0.575156
Australia         0.592989
Bangladesh        0.629794
Brazil            0.585210
Canada            0.555838
Chile             0.554034
China             0.574161
Colombia          0.585778
Egypt             0.589307
France            0.590000
Germany           0.603846
Ghana             0.552688
India             0.587273
Indonesia         0.560345
Israel            0.561132
Italy             0.572879
Japan             0.590725
Jordan            0.566517
Kenya             0.573068
Malaysia          0.571881
Mexico            0.564819
Morocco           0.595000
Nepal             0.597500
Netherlands       0.543867
New Zealand       0.574157
Nigeria           0.598736
Pakistan          0.594870
Peru              0.630300
Philippines       0.654845
Poland            0.619194
Qatar             0.589135
Saudi Arabia      0.596960
Singapore         0.555422
South Africa      0.598500
South Korea       0.621000
Spain             0.577931
Sri Lanka         0.599402
Sweden            0.617662
Taiwan            0.584591
Thailand          0.545238
UAE               0.605641
United Kingdom    0.627875
United States     0.592077
Vietnam           0.577938
Name: automation_risk_score, dtype: float64